version: "3.8"

services:
    rabbitmq:
        image: ${IMAGE:-rabbitmq:3.11.8-management}
        container_name: ${CONTAINER_NAME:-rabbitmq}
        volumes:
            - ./volumes/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia
        environment:
            RABBITMQ_DEFAULT_USER: "${DEFAULT_USER:-admin}"
            RABBITMQ_DEFAULT_PASS: "${DEFAULT_PASS:-admin}"
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        networks:
            - rabbitmq

networks:
    rabbitmq:
        name: rabbitmq
